export const REQUIRED = 'This field is required.'
export const EMAIL_NOT_EXIST = 'Email address does not exist.'
export const INVALID_EMAIL_FORMAT = 'Invalid email format.'
export const INVALID_PASSWORD_FORMAT = 'Invalid password format.'
export const INVALID_PASSWORD = 'Invalid password.'
export const SERVER_ERROR = 'Something went wrong. Please try again!'
export const PHONE_ERROR_LENGTH = 'Please enter valid phone number.'
export const API_ERROR_NOT_FOUND = '404 - Page Not Found!'
