export const REQUIRED = 'This field is required.'
export const EMAIL_NOT_EXIST = 'Email address does not exist.'
export const INVALID_EMAIL_FORMAT = 'Invalid email format.'
export const INVALID_PASSWORD_FORMAT = 'Invalid password format.'
export const INVALID_PASSWORD = 'Invalid password.'
export const SERVER_ERROR = 'Something went wrong. Please try again!'
